server:
  hostname: "0.0.0.0"
  port: 8090
  http_only: true
  public_url: "https://b029b391-50fb-49de-9264-d8924e1b1c39.e1-us-east-azure.choreoapps.dev"

gate_client:
  hostname: "b029b391-50fb-49de-9264-d8924e1b1c39.e1-us-east-azure.choreoapps.dev"
  port: 443
  scheme: "https"
  path: "/gate"

cors:
  allowed_origins:
    - "https://b029b391-50fb-49de-9264-d8924e1b1c39.e1-us-east-azure.choreoapps.dev"
    - "http://localhost:3000"


database:
  config:
    type: "postgres"
    postgres:
      hostname: "thunderid-testthethunderbot-11dd.h.aivencloud.com"
      port: 22469
      name: "configdb"
      username: "avnadmin"
      password: "{{.AIVEN_DB_PASSWORD}}"
      sslmode: "require"
      max_open_conns: 20
      max_idle_conns: 10
      conn_max_lifetime: 3600

  runtime:
    type: "postgres"
    postgres:
      hostname: "thunderid-testthethunderbot-11dd.h.aivencloud.com"
      port: 22469
      name: "runtimedb"
      username: "avnadmin"
      password: "{{.AIVEN_DB_PASSWORD}}"
      sslmode: "require"
      max_open_conns: 20
      max_idle_conns: 10
      conn_max_lifetime: 3600

  user:
    type: "postgres"
    postgres:
      hostname: "thunderid-testthethunderbot-11dd.h.aivencloud.com"
      port: 22469
      name: "userdb"
      username: "avnadmin"
      password: "{{.AIVEN_DB_PASSWORD}}"
      sslmode: "require"
      max_open_conns: 20
      max_idle_conns: 10
      conn_max_lifetime: 3600

crypto:
  encryption:
    key: "file://repository/resources/security/crypto.key"
  password_hashing:
    algorithm: "PBKDF2"
  keys:
    - id: "default-key"
      cert_file: "repository/resources/security/signing.cert"
      key_file: "repository/resources/security/signing.key"

jwt:
  preferred_key_id: "default-key"


consent:
  enabled: false
